import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './../components/Header/Header';
import Footer from './../components/Footer/Footer';
import axios from 'axios'
import { FC } from 'react'
import HomeCom from "./../components/home/HomePage"

const inter = Inter({ subsets: ['latin'] })


export interface top_blog_user {
  topUser : {
  _id: string,
  username: string,
  name: string,
  bio: string,
  avatar: string,
  averageScore: number,
  createdAt: string,
  updatedAt: string
  }[],
  topBlog: {
    _id: string,
    title: string,
    content: string,
    creatorId: string,
    imgurl: string,
    averageScore: number,
    createdAt: string,
    updatedAt: string,
    rateCount: number  
  }[]
}

const  Home:FC<top_blog_user>=({topUser, topBlog})=> {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
    <HomeCom  topUser={topUser} topBlog={topBlog}/>
    <Footer/>
    
    </>
  )
}

export default Home


export const getStaticProps = async () => {
  
  const topUser = await axios("http://localhost:4000/user/top-users");
  const topBlog = await axios("http://localhost:4000/blog/top-blogs");

  console.log(topUser)
  console.log(topBlog)

  return {
    props: {
      topUser: topUser.data,
      topBlog: topBlog.data
    }
  }

}
